/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.proheng.protocol;

@org.apache.avro.specific.AvroGenerated
public interface HelloProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"HelloProtocol\",\"namespace\":\"com.proheng.protocol\",\"types\":[{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.proheng\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"favorite_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"favorite_color\",\"type\":[\"string\",\"null\"]}]},{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"msg\",\"type\":\"string\"}]}],\"messages\":{\"hello\":{\"request\":[{\"name\":\"user\",\"type\":\"com.proheng.User\"}],\"response\":\"string\"}}}");
  /**
   */
  java.lang.CharSequence hello(com.proheng.User user);

  @SuppressWarnings("all")
  public interface Callback extends HelloProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.proheng.protocol.HelloProtocol.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void hello(com.proheng.User user, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}